# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frame_response.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='frame_response.proto',
  package='proto_messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x14\x66rame_response.proto\x12\x0eproto_messages\"\x96\x01\n\rFrameResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\r\x12\x11\n\tmeta_data\x18\x02 \x01(\t\x12\x0e\n\x06\x66rame1\x18\x03 \x01(\x0c\x12\x0e\n\x06\x66rame2\x18\x04 \x01(\x0c\x12\x0e\n\x06\x66rame3\x18\x05 \x01(\x0c\x12\x0e\n\x06\x66rame4\x18\x06 \x01(\x0c\x12\x0e\n\x06\x66rame5\x18\x07 \x01(\x0c\x12\x0e\n\x06\x66rame6\x18\x08 \x01(\x0c\x62\x06proto3'
)




_FRAMERESPONSE = _descriptor.Descriptor(
  name='FrameResponse',
  full_name='proto_messages.FrameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='proto_messages.FrameResponse.request_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meta_data', full_name='proto_messages.FrameResponse.meta_data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame1', full_name='proto_messages.FrameResponse.frame1', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame2', full_name='proto_messages.FrameResponse.frame2', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame3', full_name='proto_messages.FrameResponse.frame3', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame4', full_name='proto_messages.FrameResponse.frame4', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame5', full_name='proto_messages.FrameResponse.frame5', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame6', full_name='proto_messages.FrameResponse.frame6', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=191,
)

DESCRIPTOR.message_types_by_name['FrameResponse'] = _FRAMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FrameResponse = _reflection.GeneratedProtocolMessageType('FrameResponse', (_message.Message,), {
  'DESCRIPTOR' : _FRAMERESPONSE,
  '__module__' : 'frame_response_pb2'
  # @@protoc_insertion_point(class_scope:proto_messages.FrameResponse)
  })
_sym_db.RegisterMessage(FrameResponse)


# @@protoc_insertion_point(module_scope)
