# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frame.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='frame.proto',
  package='proto_messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0b\x66rame.proto\x12\x0eproto_messages\"\x97\x01\n\tFrameData\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\r\x12\r\n\x05\x63ycle\x18\x02 \x01(\r\x12\x10\n\x08position\x18\x03 \x01(\r\x12\x11\n\tcamera_id\x18\x04 \x01(\r\x12\r\n\x05width\x18\x05 \x01(\r\x12\x0e\n\x06height\x18\x06 \x01(\r\x12\x16\n\x0eunix_timestamp\x18\x07 \x01(\x04\x12\r\n\x05\x66rame\x18\x08 \x01(\x0c\x62\x06proto3'
)




_FRAMEDATA = _descriptor.Descriptor(
  name='FrameData',
  full_name='proto_messages.FrameData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='proto_messages.FrameData.frame_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cycle', full_name='proto_messages.FrameData.cycle', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='proto_messages.FrameData.position', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='camera_id', full_name='proto_messages.FrameData.camera_id', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='proto_messages.FrameData.width', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='proto_messages.FrameData.height', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unix_timestamp', full_name='proto_messages.FrameData.unix_timestamp', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame', full_name='proto_messages.FrameData.frame', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=183,
)

DESCRIPTOR.message_types_by_name['FrameData'] = _FRAMEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FrameData = _reflection.GeneratedProtocolMessageType('FrameData', (_message.Message,), {
  'DESCRIPTOR' : _FRAMEDATA,
  '__module__' : 'frame_pb2'
  # @@protoc_insertion_point(class_scope:proto_messages.FrameData)
  })
_sym_db.RegisterMessage(FrameData)


# @@protoc_insertion_point(module_scope)
