# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: players.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='players.proto',
  package='footplayer',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rplayers.proto\x12\nfootplayer\"\x97\x01\n\nFootPlayer\x12\n\n\x02x1\x18\x01 \x01(\x05\x12\n\n\x02x2\x18\x02 \x01(\x05\x12\n\n\x02y1\x18\x03 \x01(\x05\x12\n\n\x02y2\x18\x04 \x01(\x05\x12\x0c\n\x04x_2d\x18\x05 \x01(\x05\x12\x0c\n\x04y_2d\x18\x06 \x01(\x05\x12\x12\n\nconfidence\x18\x07 \x01(\x05\x12\r\n\x05img_w\x18\x08 \x01(\x05\x12\r\n\x05img_h\x18\t \x01(\x05\x12\x0b\n\x03img\x18\n \x01(\x0c\"\xe6\x01\n\x14\x46ootPlayerCollection\x12\r\n\x05\x63ycle\x18\x01 \x01(\x05\x12\x10\n\x08position\x18\x02 \x01(\x05\x12\x0e\n\x06\x62\x61ll_x\x18\x03 \x01(\x05\x12\x0e\n\x06\x62\x61ll_y\x18\x04 \x01(\x05\x12\x11\n\tball_x_2d\x18\x05 \x01(\x05\x12\x11\n\tball_y_2d\x18\x06 \x01(\x05\x12\x13\n\x0b\x62\x61ll_radius\x18\x07 \x01(\x05\x12\r\n\x05img_w\x18\x08 \x01(\x05\x12\r\n\x05img_h\x18\t \x01(\x05\x12\x0b\n\x03img\x18\n \x01(\x0c\x12\'\n\x07players\x18\x0b \x03(\x0b\x32\x16.footplayer.FootPlayerb\x06proto3'
)




_FOOTPLAYER = _descriptor.Descriptor(
  name='FootPlayer',
  full_name='footplayer.FootPlayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x1', full_name='footplayer.FootPlayer.x1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x2', full_name='footplayer.FootPlayer.x2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y1', full_name='footplayer.FootPlayer.y1', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y2', full_name='footplayer.FootPlayer.y2', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x_2d', full_name='footplayer.FootPlayer.x_2d', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_2d', full_name='footplayer.FootPlayer.y_2d', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='footplayer.FootPlayer.confidence', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_w', full_name='footplayer.FootPlayer.img_w', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_h', full_name='footplayer.FootPlayer.img_h', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img', full_name='footplayer.FootPlayer.img', index=9,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=181,
)


_FOOTPLAYERCOLLECTION = _descriptor.Descriptor(
  name='FootPlayerCollection',
  full_name='footplayer.FootPlayerCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cycle', full_name='footplayer.FootPlayerCollection.cycle', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='footplayer.FootPlayerCollection.position', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ball_x', full_name='footplayer.FootPlayerCollection.ball_x', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ball_y', full_name='footplayer.FootPlayerCollection.ball_y', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ball_x_2d', full_name='footplayer.FootPlayerCollection.ball_x_2d', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ball_y_2d', full_name='footplayer.FootPlayerCollection.ball_y_2d', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ball_radius', full_name='footplayer.FootPlayerCollection.ball_radius', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_w', full_name='footplayer.FootPlayerCollection.img_w', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_h', full_name='footplayer.FootPlayerCollection.img_h', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img', full_name='footplayer.FootPlayerCollection.img', index=9,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='players', full_name='footplayer.FootPlayerCollection.players', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=414,
)

_FOOTPLAYERCOLLECTION.fields_by_name['players'].message_type = _FOOTPLAYER
DESCRIPTOR.message_types_by_name['FootPlayer'] = _FOOTPLAYER
DESCRIPTOR.message_types_by_name['FootPlayerCollection'] = _FOOTPLAYERCOLLECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FootPlayer = _reflection.GeneratedProtocolMessageType('FootPlayer', (_message.Message,), {
  'DESCRIPTOR' : _FOOTPLAYER,
  '__module__' : 'players_pb2'
  # @@protoc_insertion_point(class_scope:footplayer.FootPlayer)
  })
_sym_db.RegisterMessage(FootPlayer)

FootPlayerCollection = _reflection.GeneratedProtocolMessageType('FootPlayerCollection', (_message.Message,), {
  'DESCRIPTOR' : _FOOTPLAYERCOLLECTION,
  '__module__' : 'players_pb2'
  # @@protoc_insertion_point(class_scope:footplayer.FootPlayerCollection)
  })
_sym_db.RegisterMessage(FootPlayerCollection)


# @@protoc_insertion_point(module_scope)
