# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc.proto',
  package='proto_messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\trpc.proto\x12\x0eproto_messages\"@\n\x07RPCData\x12\x12\n\nrequest_id\x18\x01 \x01(\r\x12\x11\n\tprocedure\x18\x02 \x01(\t\x12\x0e\n\x06params\x18\x03 \x01(\tb\x06proto3'
)




_RPCDATA = _descriptor.Descriptor(
  name='RPCData',
  full_name='proto_messages.RPCData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='proto_messages.RPCData.request_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='procedure', full_name='proto_messages.RPCData.procedure', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='proto_messages.RPCData.params', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['RPCData'] = _RPCDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RPCData = _reflection.GeneratedProtocolMessageType('RPCData', (_message.Message,), {
  'DESCRIPTOR' : _RPCDATA,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:proto_messages.RPCData)
  })
_sym_db.RegisterMessage(RPCData)


# @@protoc_insertion_point(module_scope)
