# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpr.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpr.proto',
  package='proto_messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\trpr.proto\x12\x0eproto_messages\"\xd2\x01\n\x07RPRData\x12\x12\n\nrequest_id\x18\x01 \x01(\r\x12\x15\n\rstr_response1\x18\x02 \x01(\t\x12\x15\n\rstr_response2\x18\x03 \x01(\t\x12\x15\n\rint_response1\x18\x04 \x01(\x04\x12\x15\n\rint_response2\x18\x05 \x01(\x04\x12\x16\n\x0e\x62yte_response1\x18\x06 \x01(\x0c\x12\x16\n\x0e\x62yte_response2\x18\x07 \x01(\x0c\x12\x17\n\x0fnbr_of_messages\x18\x08 \x01(\r\x12\x0e\n\x06msg_id\x18\t \x01(\rb\x06proto3'
)




_RPRDATA = _descriptor.Descriptor(
  name='RPRData',
  full_name='proto_messages.RPRData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='proto_messages.RPRData.request_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='str_response1', full_name='proto_messages.RPRData.str_response1', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='str_response2', full_name='proto_messages.RPRData.str_response2', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int_response1', full_name='proto_messages.RPRData.int_response1', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int_response2', full_name='proto_messages.RPRData.int_response2', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='byte_response1', full_name='proto_messages.RPRData.byte_response1', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='byte_response2', full_name='proto_messages.RPRData.byte_response2', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nbr_of_messages', full_name='proto_messages.RPRData.nbr_of_messages', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_id', full_name='proto_messages.RPRData.msg_id', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=240,
)

DESCRIPTOR.message_types_by_name['RPRData'] = _RPRDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RPRData = _reflection.GeneratedProtocolMessageType('RPRData', (_message.Message,), {
  'DESCRIPTOR' : _RPRDATA,
  '__module__' : 'rpr_pb2'
  # @@protoc_insertion_point(class_scope:proto_messages.RPRData)
  })
_sym_db.RegisterMessage(RPRData)


# @@protoc_insertion_point(module_scope)
